steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'donate', '--trigger-http', '--runtime=${_RUNTIME}', '--source=${_SOURCE}', '--env-vars-file=FaaS/.env.yaml']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'add-iam-policy-binding', 'donate', '--member=allUsers', '--role=${_ROLE}']
substitutions:
  _SOURCE: https://source.cloud.google.com/nih-nci-dceg-episphere-dev/github_episphere_donate/+/faas:FaaS/
  _RUNTIME: nodejs14
  _ROLE: roles/cloudfunctions.invoker